name: test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - id: make-cache-key
        run: |
          echo "::set-output name=cpuflags::$(lscpu -J | jq -r '.lscpu[] | select(.field=="Flags:") | .data | gsub("[^a-z0-9]"; "")')"
      - uses: actions/cache@v2
        with:
          path: |
            ~/setup-dpdk.cache.*
          key: ${{ steps.make-cache-key.outputs.cpuflags }}
      - uses: actions/checkout@v2
      - uses: ./
        with:
          dpdk-version: "20.08"
          spdk-version: "20.07"
          hugepages: 1024
      - run: find /usr/local/bin -name 'dpdk*' -or -name 'spdk*'
